In [ ]:
# !pip install geonamescache

In [ ]:
import pandas as pd
import geonamescache
import re
from unidecode import unidecode

In [ ]:
# get and view dataset; convert to pandas dataframe
data = pd.read_csv("data/headlines.txt", sep="\n", names=['headline', 'countries', 'cities'])
data.head(10)

In [22]:
# get names oc countries and cities to match against; convert to dataframe
gc = geonamescache.GeonamesCache()
countries = gc.get_countries()
countries = pd.DataFrame.from_dict(countries, orient='index')
cities = gc.get_cities()
cities = pd.DataFrame.from_dict(cities, orient='index')

In [23]:
# 1. clean up country names
country_names = unidecode(countries['name'].str.cat(sep = "|")
                          .replace(" ", "\s")
                          .replace("-", "\-"))

# 2. build a regex with all country names
regexp_country = f"(?i)({country_names})"

# 3. extract matches using the above regex and populate countries column in dataframe
data['countries'] = data['headline'].astype('str').str.extract(regexp_country, expand=True)

# repeat above 3 steps for cities column
city_names = unidecode(cities['name'].str.cat(sep = "|")
                       .replace(" ", "\s")
                       .replace("-", "\-")
                      .replace("`", "")
                      .replace("|", r"\b|\b"))
regexp_city = f"({city_names})"
data['cities'] = data['headline'].astype('str').str.extract(regexp_city, expand=True)

In [24]:
# view final result
data

,headline,countries,cities
0,Zika Outbreak Hits Miami,NaN,Miami
1,Could Zika Reach New York City?,NaN,New York City
2,First Case of Zika in Miami Beach,NaN,Miami
3,"Mystery Virus Spreads in Recife, Brazil",Brazil,Recife
4,Dallas man comes down with case of Zika,NaN,Dallas
5,Trinidad confirms first Zika case,NaN,Trinidad
6,Zika Concerns are Spreading in Houston,NaN,Houston
7,Geneve Scientists Battle to Find Cure,NaN,Geneve
8,The CDC in Atlanta is Growing Worried,NaN,Atlanta
9,Zika Infested Monkeys in Sao Paulo,NaN,Sao Paulo
10,Brownsville teen contracts Zika virus,NaN,Brownsville
11,Mosquito control efforts in St. Louis take new...,NaN,St. Louis
12,San Juan reports 1st U.S. Zika-related death a...,NaN,San Juan
13,"Flu outbreak in Galveston, Texas",NaN,Galveston
14,Zika alert â€“ Manila now threatened,NaN,Manila
15,Zika afflicts 7 in Iloilo City,NaN,Iloilo
16,New Los Angeles Hairstyle goes Viral,NaN,Los Angeles
17,Louisiana Zika cases up to 26,NaN,NaN
18,Orlando volunteers aid Zika research,NaN,Orlando
19,Zika infects pregnant woman in Cebu,oman,NaN
20,Chicago's First Zika Case Confirmed,NaN,Chicago
21,Tampa Bay Area Zika Case Count Climbs,NaN,Tampa
22,"Bad Water Leads to Sickness in Flint, Michigan",NaN,Flint
23,Baltimore plans for Zika virus,NaN,Baltimore
24,London Health Unit Tracks Mad Cow Disease,NaN,London
25,Zika cases in Vietnam's Ho Chi Minh City surge,Vietnam,Ho
26,Philadelphia experts track pandemic,NaN,Philadelphia
27,Flu season hits Boston,NaN,Boston
28,Scientists in Paris to look for answers,NaN,Paris
29,Key Zika Findings in San Diego Institute,NaN,San Diego
...,...,...,...
620,How to Avoid Chikungunya in Hampton,NaN,Hampton
621,Zika Reported in Sao Jose,NaN,Sao Jose
622,Case of Norovirus Reported in Stratford,NaN,Stratford
623,How to Avoid Hepatitis E in South Bend,NaN,South Bend
624,Hepatitis C Outbreak in Bethlehem,NaN,Bethlehem
625,Davenport is infested with Dengue,NaN,Davenport
626,Rumors about Swine Flu spreading in Suzhou hav...,NaN,Suzhou
627,Malaria Vaccine is now Required in Elyria,NaN,Elyria
628,Zika case reported in Antioquia,NaN,NaN
629,Case of Swine Flu Reported in Tbilisi,NaN,Tbilisi
630,Chikungunya has not Left Pismo Beach,NaN,NaN
631,Zika spreads to La Joya,NaN,NaN
632,Influenza Keeps Spreading in Suffolk,NaN,Suffolk
633,More people in Allentown are infected with Chl...,NaN,Allentown
634,Mad Cow Disease re-emerges in Bedford,NaN,Bedford
635,Authorities are Worried about the Spread of He...,NaN,Yiwu
636,Zika Outbreak in Yurimaguas,NaN,Yurimaguas
637,Dengue Outbreak in Easton,NaN,Easton
638,Varicella has Arrived in Milton,NaN,Milton
639,New medicine wipes out Meningitis in Sevilla,NaN,Sevilla
640,Authorities are Worried about the Spread of Va...,NaN,Clovis
641,More Zika patients reported in Fort Worth,NaN,Fort Worth
642,Zika symptoms spotted in Boynton Beach,NaN,Boynton Beach
643,Outbreak of Zika in Portoviejo,NaN,Portoviejo
644,Influenza Exposure in Muscat,NaN,Muscat
645,Rumors about Rabies spreading in Jerusalem hav...,NaN,Jerusalem
646,More Zika patients reported in Indang,NaN,Indang
647,Suva authorities confirmed the spread of Rotav...,NaN,Suva
648,More Zika patients reported in Bella Vista,NaN,Bella Vista
649,Zika Outbreak in Wichita Falls,NaN,Wichita